# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: false
  JavaScript: false
  PHP: true
  Python: false
exclude_paths:
- "test/*"
- "docs/*"
- "examples/*"
- "scripts/*"
checks:
  argument-count:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
