# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

addons:
  mariadb: '10.0'

# list any PHP version you want to test against
php:
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  - 7
  # hhvm
  #- hhvm

before_script:
  - mkdir -p build/logs
  - sudo apt-get install mariadb-oqgraph-engine-10.0
  - sudo mysql < ./scripts/oqgraph.sql
  - sudo mysql < ./scripts/test-user.sql
  - ./createdb.sh test test test
  - composer install --no-interaction
  #- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  #- chmod +x ./cc-test-reporter
  #- ./cc-test-reporter before-build

script:
  - vendor/phpunit/phpunit/phpunit --configuration ./phpunit.travis.xml test/php

after_success:
  #- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "ashley@zf4.biz"

