# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

#addons:
#  mariadb: '10.0'

# list any PHP version you want to test against
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  # hhvm
  #- hhvm

env:
  - DB=mysql
  - DB=mariadb

before_install:
  - sudo apt-get update > /dev/null
  - composer self-update
  - PHPVER=$(php -v | grep  -P --only-matching "\\d+\.\\d+" | head -n 1)
  - if [[ "$DB" = "mariadb" && 5.6 = $PHPVER ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi;
  - if [[ "$DB" = "mariadb" && 5.6 = $PHPVER ]]; then chmod +x ./cc-test-reporter; fi;

install:
  - if [[ "$DB" = "mariadb" ]]; then ./scripts/travis.install.mariadb.sh; fi;
  - if [[ "$DB" = "mysql" ]]; then ./scripts/travis.install.mysql.sh; fi;

before_script:
  - mkdir -p build/logs
  - composer install --no-interaction
  - if [[ "$DB" = "mariadb" && 5.6 = $PHPVER ]]; then ./cc-test-reporter before-build; fi;

script:
  - vendor/phpunit/phpunit/phpunit --configuration ./phpunit.travis.xml test/php

after_success:
  - if [ "$DB" = "mysql" && 5.6 = $PHPVER ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi;

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "ashley@zf4.biz"

